### ISSUE TITLE
cell tags toolbar without modifying config file?

### ISSUE THREAD

**Issue by JohnGriffiths** [jdfreder/notebook_cherry_picker#4]
I know this is an old repo now, but I've been using some derivative code from it for a while now that has proved very useful. 

The only thing that makes it a bit of a faff to use is the need to modify ones config file to get the cell tags toolbar. 

I was just wondering whether you knew if it might be possible now in ipython/jupyter to do add the cell tags toolbar directly; e.g. via a cell, function, magic extension, etc. ?

Ta,

john

**Comment by jdfreder** [comment]
Hi John,

There's a PR open in master for that.  It will be added soon.

https://github.com/jupyter/notebook/issues/601
